name: "Deploy AKS cluster with Terraform"
on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.TFSTATE_RESOURCE_GROUP }}
  STORAGE_ACCOUNT: ${{ secrets.TFSTATE_STORAGE_ACCOUNT }}
  CONTAINER_NAME: ${{ secrets.TFSTATE_CONTAINER_NAME }}
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform_aks
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install Terraform on runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4
          
      #- name: Terraform Init
        #run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
          

